name: django-jsonform tests

on:
  pull_request:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        django-version: ["2.2", "3.2", "4.1", "4.2", "main"]
        exclude:
          - django-version: 2.2
            python-version: 3.10
          - django-version: 2.2
            python-version: 3.11
          - django-version: 3.2
            python-version: 3.11
          - django-version: 4.1
            python-version: 3.7
          - django-version: 4.2
            python-version: 3.7
          - django-version: "main"
            python-version: 3.7
          - django-version: "main"
            python-version: 3.8
          - django-version: "main"
            python-version: 3.9

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install Django ${{ matrix.django-version }}
        run: python -m pip install django~=${{ matrix.django-version }}.0
        if: matrix.django-version != 'main'
      - name: Install Django main
        run: python -m pip install https://github.com/django/django/archive/refs/heads/main.zip
        if: matrix.django-version == 'main'
      - name: Install library to run tests
        run: python -m pip install -e .
      - name: Verify versions
        run: |
          python --version
          python -c "import django ; print(django.VERSION)"
      - name: Run tests
        run: |
          python -m pip install coverage
          coverage run tests/__main__.py
          coverage report -m
